### ISSUE TITLE
Duplicate implementations of `pvalue`.

### ISSUE THREAD

**Issue by peter-mlabs** [Liqwid-Labs/liqwid-plutarch-extra#1]
See [here](https://github.com/Liqwid-Labs/liqwid-plutarch-extra/blob/755fb7ccddc8f4b84b38d1fd939ec0ddec945eec/src/Plutarch/Api/V1/AssetClass.hs#L107) and [here](https://github.com/Liqwid-Labs/liqwid-plutarch-extra/blob/755fb7ccddc8f4b84b38d1fd939ec0ddec945eec/src/Plutarch/Api/V1/Value.hs#L58). 

These both may be affected by the work in https://github.com/mlabs-haskell/liqwid-onchain/issues/24 as well.

We need to 
- [ ] Determine which should be used
- [ ] Remove the other(s)

**Comment by kozross** [comment]
This has been resolved: there's no `pvalue` in LPE now. Closing.
