### ISSUE TITLE
PInner Monoid instance in Plutarch.Orphans causes (plutarch-compile-time) infinite loops where (PInner a ~ a)

### ISSUE THREAD

**Issue by t1lde** [Liqwid-Labs/liqwid-plutarch-extra#113]
See: https://github.com/Liqwid-Labs/liqwid-plutarch-extra/blob/fe341f0483b9da2ec4990c8617ecb113ed94c316/src/Plutarch/Orphans.hs#L54-L68

This causes most types without Monoid/Semigroup instances to erroneously receive instances!

For example - the following cause an infinite loop at plutarch compile time:

```haskell
printTerm (Config DoTracing) (d :: Term s PScriptContext)
printTerm (Config DoTracing) (d :: Term s PDatum)
```

This is due to most of the Builtin types having (PInner a ~ a), so effectively every type will cause such looping !

**Comment by peter-mlabs** [comment]
Fascinating. How did you track this down?
