### ISSUE TITLE
Changelog In Chronological Order

### ISSUE THREAD

**Issue by tbidne** [Liqwid-Labs/liqwid-plutarch-extra#15]
While contemplating a change to accompany another PR, I noticed the [changelog](https://github.com/Liqwid-Labs/liqwid-plutarch-extra/blob/30f66917823a534c322ff880c16aa2d607b4bba6/CHANGELOG.md) is currently in chronological order:

> ## 1.0.0 -- 2022-05-24
> ...
> ## 1.1.0 -- 2022-06-17
> ...

Is this intentional? The referenced `Keep A Changelog` wants reverse chronological order, which matches my expectations. I am happy to make a quick PR if this is indeed an oversight.

Thanks!

**Comment by SeungheonOh** [comment]
Fixed
