### ISSUE TITLE
`PType` and `S -> Type`

### ISSUE THREAD

**Issue by SeungheonOh** [Liqwid-Labs/liqwid-plutarch-extra#34]
First they are the same thing:
```hs
type PType = S -> Type
```

These two identical but differently written statements are scattered all over LPE. Changing one to the other would help overall readability of our code base. Personally, `PType` seems like a better option.

**Comment by SeungheonOh** [comment]
Bump: @kozross @peter-mlabs

**Comment by peter-mlabs** [comment]
As Koz mentioned in the slack, let's go for `S -> Type` to improve error messages
