### ISSUE TITLE
Duplicate implementations of `punionWith`

### ISSUE THREAD

**Issue by peter-mlabs** [Liqwid-Labs/liqwid-plutarch-extra#44]
`punionWith` appears in both Plutarch itself and LPE (for both sorted and unsorted varieties).

**Comment by peter-mlabs** [comment]
Actually, I'm realizing that there's duplicate functions in plutarch itself (one in `Value` and one in `Assoc` map). Just going to leave this issue up as a reminder to check whether any of our instances duplicate their instances.

**Comment by kozross** [comment]
This seems to already be resolved: we don't have `punionWith` in LPE. Closing.
