### ISSUE TITLE
`PartialTypeSignatures` is enabled in `Plutarch.Extra.List`

### ISSUE THREAD

**Issue by peter-mlabs** [Liqwid-Labs/liqwid-plutarch-extra#56]
This is against the Standards.

The offending line (or at least one of them) is [here](https://github.com/Liqwid-Labs/liqwid-plutarch-extra/blob/d8be5f8dc91ad00158727fdbccb6db849e9f3559/src/Plutarch/Extra/List.hs#L119).

**Comment by peter-mlabs** [comment]
@kozross, you've mentioned before that these wildcards should not be necessary -- but I've never been able to figure out what we're supposed to do here.

**Comment by kozross** [comment]
Explicit `forall`s for a different `s`. I've done it in a few places.

**Comment by kozross** [comment]
This is now resolved.
