### ISSUE TITLE
Remove all use of SOP generics

### ISSUE THREAD

**Issue by kozross** [Liqwid-Labs/liqwid-plutarch-extra#64]
Now that we're using Plutarch 1.2, we no longer need SOP generics support. While PR #63 eliminates almost all of these, one module (`Plutarch.Extra.IsData`) still makes heavy use of SOP generics.

@t1lde @chfanghr - according to `git blame`, this code is something you two contributed. Would you be OK with changing this to use GHC generics rather than SOP ones?

**Comment by chfanghr** [comment]
I personally not very familiar with `GHC.Generics` but it's okay to replace the SOP ones, I supposed.
