### ISSUE TITLE
Upstream some stuff to Plutarch

### ISSUE THREAD

**Issue by kozross** [Liqwid-Labs/liqwid-plutarch-extra#67]
This is a 'meta-issue' listing modules which may be good candidates for easy upstreaming. Specifically, they don't require upstreaming type classes, and aren't particularly opinionated.

* `Plutarch.Orphans`
* `Plutarch.Extra.AssetClass`
* `Plutarch.Extra.Bool`
* `Plutarch.Extra.ScriptContext`
* `Plutarch.Extra.TermCont`
* `Plutarch.Extra.Tuple`

**Comment by peter-mlabs** [comment]
moved to notion https://www.notion.so/liqwid/Upstream-some-stuff-to-plutarch-2a28c6b5c6f14e5cb2a64efe42ce796c
