### ISSUE TITLE
Add usage examples in haddock for `DerivePConstantViaDataList`

### ISSUE THREAD

**Issue by peter-mlabs** [Liqwid-Labs/liqwid-plutarch-extra#75]

**Comment by kozross** [comment]
This requires rewriting to use GHC generics, so we can combine those efforts.

**Comment by peter-mlabs** [comment]
Closing as moved to notion: https://www.notion.so/liqwid/Add-usage-examples-in-haddock-for-DerivePConstantViaDataList-6ae951f2f67445d5a04e06f2cd9832ff
