### ISSUE TITLE
Better way to have "Sorted" list

### ISSUE THREAD

**Issue by SeungheonOh** [Liqwid-Labs/liqwid-plutarch-extra#81]
Possibilities:
- Separate type: Ex) `PSortedList`
  - This is the "simplest" solution
  - Should it be Data Plut or Scott Plut?
  - If we need both, we need two types (Doesn't seem neat)
- Ghost of Departed Proofs
  - We get fully customizable proof system. 
  - It's quite beyond the scope of making "sorted list".
- Providing different constraint. 
  - I'm not sure if it's possible.

**Comment by SeungheonOh** [comment]
Seems like we want the first option. 
There will be two types one for each categories. Module will provide list conversion function as `pconvertLists` will be slower(O(N)).

**Comment by peter-mlabs** [comment]
closed as moved to notion: 
https://www.notion.so/liqwid/Better-way-to-have-Sorted-list-1ab29c3c1e99442f83640988e22459b2
